numeros = input().split()
a = int(numeros[0])
b = int(numeros[1])
c = int(numeros[2])
lista = [a, b, c]
lista.sort()
print(lista[0])
print(lista[1])
print(lista[2])
print()
print(a)
print(b)
print(c)
